apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend-gateway
spec:
  servers:
    - hosts:
        - "onlineboutique.example.com"
      port:
        name: http2
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: onlineboutique-credential