apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myrb
  namespace: kube-system
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-read-clusterrole
subjects:
- kind: ServiceAccount
  name: kubectl-pod-sa
  namespace: default
