apiVersion: batch/v1
kind: Job 
metadata:
  annotations:
    "helm.sh/hook": post-delete
  name: {{ include "resource-name" . }}-job
  labels:
      {{- include "app-labels" . | nindent 4 }}
spec:
  template:
      spec:
        containers:
          - name: post-delete-container
            image: busybox
            command: ['echo']
            args: ['I am done with cleanup!'] 
        restartPolicy: Never