apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
       app: argocd-demo
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
     containers:
        - name: nginx
          image: nginx
