apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend-gateway
spec:
  servers:
    - hosts:
        - "onlineboutique.example.com"
      port:
        name: http
        number: 80
        protocol: HTTP