---
apiVersion: v1
kind: Secret
metadata:
  name: secretdemo
data:
  PASSWORD: cGFzc3dvcmQ= 
  USERNAME: YWRtaW4= 
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: secretdemopod
spec:
  containers:
    - name: demopod
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secretdemo
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretdemo
              key: PASSWORD
