apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev-cluster
        url: https://kubernetes.default.svc
        namespace: dev
      - cluster: stage-cluster
        url: https://172.18.0.2:31413
        namespace: stage
    selector:
      matchLabels:
        namespace: stage
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: git@github.com:ppratheesh/ArgoCD-demo.git
        targetRevision: HEAD
        path: nginx
        directory:
          recurse: true
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true 
