apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-guestbook
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
              repoURL: https://github.com/ppratheesh/Tasks.git
              revision: HEAD
              directories:
                - path: ArgoCD/apps/*
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/ppratheesh/Tasks.git
        targetRevision: HEAD
        path: '{{path}}'
      destination: 
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

