apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: frontend
spec:
  containers:
  - name: webserver
    image: nginx
    startupProbe:
      httpGet:
         path: /web.txt
         port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 10

    readinessProbe:
      httpGet:
         path: /web.txt
         port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    
    livenessProbe:
      httpGet:
        path: /web.txt
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
      - name: my-vol
        mountPath: /usr/share/nginx/html

  initContainers:
  - name: init-file
    image: busybox
    command: ['sh','-c','touch /usr/share/nginx/html/web.txt']
    volumeMounts:
     - name: my-vol
       mountPath: /usr/share/nginx/html


  volumes:
   - name: my-vol
     emptyDir: {}

